name: Daily Scraper

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

env:
  VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
  VITE_SUPABASE_ANON_KEY: ${{secrets.VITE_SUPABASE_ANON_KEY}}

jobs:
  run-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run batch script
        run: npm run batch
